### ISSUE TITLE
Code with $ start character

### ISSUE THREAD

**Issue by sniton** [Moeditor/Moeditor#5]
```php
$this->title = "foo";
```

$ prevent code synthax for the line and all the lines after.

**Comment by Menci** [comment]
It's a bug with Moeditor's math rendering and CodeMirror configure.

**Comment by Menci** [comment]
If there's a single `$` in a inline code or code block, we'll got the `TeX parse error`, and If we type a math equation in that, the math will be rendered "correctlly" (even it'll be colored in a code block).

Moeditor's math renderer separates all `$ ... $`s and `$$ ... $$`s from MD, rendered the MD to HTML with marked and replace the maths with rendered. So I must detect the codes and not catch maths in them.

Another problem is CodeMirror's highlight, they are highlighted as LaTeX instead of code, I am condiering a better CodeMirror configure to avoid this.

**Comment by Menci** [comment]
The bug in renderer was fixed in https://github.com/Moeditor/Moeditor/commit/f35ef062b9350b673a52da204a551475251d3a22, and the editor's bug is remaining.
